Say you have certain assets a[i], each costing r[i] per item. And you would like to get a balanced portfolio of them where a[i] would take ratio t[i] (sum of t[i] should be 1). Right now they are unbalanced, so the task is to find such d[i], i.e. the amount of asset[i] to additionally buy, so that the ratio of such increased a[i] would be t[i] in increased portfolio.

In [17]:
a=[10,1,1]
r=[1,90,80]
t=[0.33,0.33,1-0.66]

In [18]:
M=[]
for i in range(len(a)):
    line = [r[i]*(1-t[i]) if j == i else -t[i]*r[j] for j in range(len(a))]
    M.append(line)

In [28]:
b=[]
for i in range(len(a)):
    sm = 0
    for j in range(len(a)):
        if (j != i):
            sm += a[j]*r[j]
    line = a[i]*r[i]*(t[i]-1) + t[i] * sm
    b.append(line)

In [26]:
M

[[0.6699999999999999, -29.700000000000003, -26.400000000000002],
 [-0.33, 60.3, -26.400000000000002],
 [-0.33999999999999997, -30.599999999999998, 52.800000000000004]]

In [29]:
b

[49.400000000000006, -30.599999999999994, -18.800000000000004]

In [6]:
import numpy as np

In [20]:
npM = np.matrix(M)

In [21]:
npM

matrix([[  0.67, -29.7 , -26.4 ],
        [ -0.33,  60.3 , -26.4 ],
        [ -0.34, -30.6 ,  52.8 ]])

In [22]:
npM.I

matrix([[-1.77494809e+16, -1.77494809e+16, -1.77494809e+16],
        [-1.97216454e+14, -1.97216454e+14, -1.97216454e+14],
        [-2.28591799e+14, -2.28591799e+14, -2.28591799e+14]])

In [31]:
npb = np.array(b)

In [32]:
d=np.linalg.solve(npM, npb)

In [33]:
d

array([-93.41176471,  -1.92679739,  -2.07424242])